# Generated by Django 3.2 on 2023-02-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Вин'),
        ),
    ]
